### PR TITLE
Changes to Single Machine Setup Readme

### PR DESCRIPTION
**Pull request by avpeery**
Updates instructions on single machine install to run all OpenFIDO services together.

### CODE REVIEW

**Review by dchassin — CHANGES_REQUESTED** [review]
1. The repositories no longer need to be private.  I've made them public so we can remove the part about the key access.
2. You should include any `cd` commands or other seemingly trivial commands.  Assume nothing about the experience of the reader.  Also, make sure that any platform specific variants are noted.
3. It doesn't say anywhere that `conda` is needed. Installation of `conda` when `gridlabd` is installed is a particular issue since they may conflict with each if `conda` is installed in `/usr/local`.
4. The command `docker-compose build --build-arg SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)"` refers to a file that does not exist. I was unable to verify the rest of the process because of that. I think you have to enter either change this `id_rsa` to `id_ed25519` or tell the user to name the file `~/.ssh/id_ed15519`

Here is a transcript of my attempt:
~~~
openfido-auth-service$ cd openfido-auth-service
openfido$ export DOCKER_BUILDKIT=1
openfido$ export COMPOSE_DOCKER_CLI_BUILD=1
openfido-auth-service$ cp ../openfido-auth-service/.env.example .auth-env
openfido-auth-service$ touch .worker-env
openfido-auth-service$ touch ../openfido-auth-service/.env
openfido-auth-service$ ssh-keygen -t ed25519 -C "********"
Generating public/private ed25519 key pair.
Enter file in which to save the key (/Users/********/.ssh/id_ed25519): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /Users/********/.ssh/id_ed25519.
Your public key has been saved in /Users/********/.ssh/id_ed25519.pub.
********
openfido-auth-service$ docker-compose build --build-arg SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)"
cat: /Users/********/.ssh/id_rsa: No such file or directory
auth-db uses an image, skipping
authstorage uses an image, skipping
WARNING: Native build is an experimental feature and could change at any time
Building auth-service
[+] Building 58.5s (25/27)                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                  0.0s
 => => transferring dockerfile: 1.11kB                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                     0.0s
 => => transferring context: 2B                                                                                                       0.0s
 => resolve image config for docker.io/docker/dockerfile:1.0.0-experimental                                                           2.1s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                                      0.0s
 => docker-image://docker.io/docker/dockerfile:1.0.0-experimental@sha256:d2d402b6fa1dae752f8c688d72066a912d7042cc1727213f7990cdb57f6  0.9s
 => => resolve docker.io/docker/dockerfile:1.0.0-experimental@sha256:d2d402b6fa1dae752f8c688d72066a912d7042cc1727213f7990cdb57f60df0  0.0s
 => => sha256:0ebbea2400fa95b4fbbef60efc694402c078d6bcab7ee2b476bb17ac9af3dfaa 637B / 637B                                            0.0s
 => => sha256:d3bb83eb682ffd2e30a5c8a89b86d60fd348e09be8301d8c28cf0b58ebf61412 7.54MB / 7.54MB                                        0.7s
 => => sha256:d2d402b6fa1dae752f8c688d72066a912d7042cc1727213f7990cdb57f60df0c 2.03kB / 2.03kB                                        0.0s
 => => sha256:da42ab0d8238dd86f7669b0ce43bb0a2d0f8bb55147eadc3073760429b703899 527B / 527B                                            0.0s
 => => extracting sha256:d3bb83eb682ffd2e30a5c8a89b86d60fd348e09be8301d8c28cf0b58ebf61412                                             0.1s
 => [internal] load build definition from Dockerfile                                                                                  0.0s
 => => transferring dockerfile: 1.11kB                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                     0.0s
 => => transferring context: 2B                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim                                                                    1.5s
 => [auth] library/python:pull token for registry-1.docker.io                                                                         0.0s
 => [internal] helper image for file operations                                                                                       0.5s
 => => resolve docker.io/docker/dockerfile-copy:v0.1.9@sha256:e8f159d3f00786604b93c675ee2783f8dc194bb565e61ca5788f6a6e9d304061        0.0s
 => => sha256:f7b6696c3fee7264ec4486cebe146a6a98aa8d1e46747843107ff473aada8d56 861.00kB / 861.00kB                                    0.4s
 => => sha256:e8f159d3f00786604b93c675ee2783f8dc194bb565e61ca5788f6a6e9d304061 2.03kB / 2.03kB                                        0.0s
 => => sha256:a546a4352bcaa6512f885d24fef3d9819e70551b98535ed1995e4b567ac6d05b 736B / 736B                                            0.0s
 => => sha256:494e63343c3f0d392e7af8d718979262baec9496a23e97ad110d62b9c90d6182 766B / 766B                                            0.0s
 => => sha256:df3b4bed1f63b36992540a09e0d10bd3f9d0b082d50810313841d745d7cce368 898.21kB / 898.21kB                                    0.3s
 => => extracting sha256:df3b4bed1f63b36992540a09e0d10bd3f9d0b082d50810313841d745d7cce368                                             0.1s
 => => extracting sha256:f7b6696c3fee7264ec4486cebe146a6a98aa8d1e46747843107ff473aada8d56                                             0.1s
 => [internal] load build context                                                                                                     0.0s
 => => transferring context: 415.23kB                                                                                                 0.0s
 => [base 1/1] FROM docker.io/library/python:3.8-slim@sha256:cede59c0e2fcbabed9b3094f1564917632ecdd11c25c2a275654946938225ef4         3.9s
 => => resolve docker.io/library/python:3.8-slim@sha256:cede59c0e2fcbabed9b3094f1564917632ecdd11c25c2a275654946938225ef4              0.0s
 => => sha256:cede59c0e2fcbabed9b3094f1564917632ecdd11c25c2a275654946938225ef4 1.86kB / 1.86kB                                        0.0s
 => => sha256:06f2b34e0a84cf236c68c11c302b7a5a6a4a89db09ba30284223b82fb6428a2a 1.37kB / 1.37kB                                        0.0s
 => => sha256:4fab6f68e9f062197afc49840ca8cd77a10a19652ace76106f19227785d1a637 7.65kB / 7.65kB                                        0.0s
 => => sha256:6ec7b7d162b24bd6df88abde89ceb6d7bbc2be927f025c9dd061af2b0c328cfe 27.10MB / 27.10MB                                      2.2s
 => => sha256:80ff6536d04b44548c6b469e46e74013f30644af5fe48d7eb611c67077bb3ee9 2.75MB / 2.75MB                                        0.6s
 => => sha256:dae9b9db2aa95ff537693a1bf49c121acabba73aecf7604f2db791eca4f9aca6 10.68MB / 10.68MB                                      1.3s
 => => sha256:e97f9ed0e1d36fe45b1436656615cb0495d557a9debf34344279a5334ac4087d 233B / 233B                                            0.8s
 => => sha256:865ac45b2a45997999552ecf749efb853b72df04c84ae8f1c400b737cf15a0fc 3.49MB / 3.49MB                                        1.4s
 => => extracting sha256:6ec7b7d162b24bd6df88abde89ceb6d7bbc2be927f025c9dd061af2b0c328cfe                                             0.8s
 => => extracting sha256:80ff6536d04b44548c6b469e46e74013f30644af5fe48d7eb611c67077bb3ee9                                             0.1s
 => => extracting sha256:dae9b9db2aa95ff537693a1bf49c121acabba73aecf7604f2db791eca4f9aca6                                             0.3s
 => => extracting sha256:e97f9ed0e1d36fe45b1436656615cb0495d557a9debf34344279a5334ac4087d                                             0.0s
 => => extracting sha256:865ac45b2a45997999552ecf749efb853b72df04c84ae8f1c400b737cf15a0fc                                             0.2s
 => [auth] docker/dockerfile-copy:pull token for registry-1.docker.io                                                                 0.0s
 => [python-deps 1/10] RUN apt-get update -qq && apt-get install -y ssh git                                                          12.5s
 => [runtime 1/4] RUN apt-get update -qq &&   apt-get install -y pipenv   postgresql-client   curl   &&   apt-get clean              38.8s
 => [python-deps 2/10] RUN mkdir /root/.ssh/                                                                                          0.3s
 => [python-deps 3/10] RUN echo "" > /root/.ssh/id_rsa                                                                                0.3s
 => [python-deps 4/10] RUN chmod 600 /root/.ssh/id_rsa                                                                                0.3s
 => [python-deps 5/10] RUN touch /root/.ssh/known_hosts                                                                               0.3s
 => [python-deps 6/10] RUN ssh-keyscan github.com >> /root/.ssh/known_hosts                                                           0.5s
 => [python-deps 7/10] ADD Pipfile .                                                                                                  0.2s
 => [python-deps 8/10] ADD Pipfile.lock .                                                                                             0.2s
 => [python-deps 9/10] RUN pip install pipenv                                                                                         5.7s
 => ERROR [python-deps 10/10] RUN --mount=type=ssh PIPENV_VENV_IN_PROJECT=1 pipenv install --dev --deploy                            29.3s
 => [runtime 2/4] RUN mkdir /opt/app                                                                                                  0.4s
------
 > [python-deps 10/10] RUN --mount=type=ssh PIPENV_VENV_IN_PROJECT=1 pipenv install --dev --deploy:
#24 0.954 Creating a virtualenv for this project...
#24 0.954 Pipfile: /Pipfile
#24 0.968 Using /usr/local/bin/python3.8 (3.8.7) to create virtualenv...
⠧ Creating virtual environment...created virtual environment CPython3.8.7.final.0-64 in 469ms
#24 1.549   creator CPython3Posix(dest=/.venv, clear=False, no_vcs_ignore=False, global=False)
#24 1.549   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
#24 1.549     added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
#24 1.549   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
#24 1.549 
#24 1.615✔ Successfully created virtual environment! 
#24 1.724 Virtualenv location: /.venv
#24 1.782 Installing dependencies from Pipfile.lock (3e5d91)...
#24 27.98 An error occurred while installing -e git+ssh://git@github.com/slacgismo/openfido-utils.git@6544e1878690c41c4d064f476bb82559905b4e56#egg=openfido-utils! Will try again.
#24 27.98 Installing initially failed dependencies...
#24 29.00 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/cli/command.py", line 233, in install
#24 29.00 [InstallError]:       retcode = do_install(
#24 29.00 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 2052, in do_install
#24 29.00 [InstallError]:       do_init(
#24 29.00 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 1304, in do_init
#24 29.00 [InstallError]:       do_install_dependencies(
#24 29.00 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 899, in do_install_dependencies
#24 29.00 [InstallError]:       batch_install(
#24 29.00 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 796, in batch_install
#24 29.00 [InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
#24 29.00 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 703, in _cleanup_procs
#24 29.00 [InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
#24 29.00 [pipenv.exceptions.InstallError]: Obtaining openfido-utils from git+ssh://****@github.com/slacgismo/openfido-utils.git@6544e1878690c41c4d064f476bb82559905b4e56#egg=openfido-utils (from -r /tmp/pipenv-19_dt0pz-requirements/pipenv-8mrwfxtq-requirement.txt (line 1))
#24 29.00 [pipenv.exceptions.InstallError]:   Cloning ssh://****@github.com/slacgismo/openfido-utils.git (to revision 6544e1878690c41c4d064f476bb82559905b4e56) to /.venv/src/openfido-utils
#24 29.00 [pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/slacgismo/openfido-utils.git' /.venv/src/openfido-utils Check the logs for full command output.
#24 29.00 ERROR: Couldn't install package: openfido-utils
#24 29.00  Package installation failed...
------
executor failed running [/bin/sh -c PIPENV_VENV_IN_PROJECT=1 pipenv install --dev --deploy]: exit code: 1
ERROR: Service 'auth-service' failed to build
~~~

**Comment by dchassin** [comment]
Question: would it possible to create a single `sh` script that does all this for the user?

**Comment by dchassin** [comment]
We also need to include a prerequisites list. It apparently includes at least the following on Darwin: 
~~~
xcode-select install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install openssl@1.1 
~~~

They also need to install and configure docker. We should give any needed tips on docker setup if the defaults setup won't work.

**Comment by avpeery** [comment]
> Here is a transcript of my attempt:
> 
> ```
> ********
> openfido-auth-service$ docker-compose build --build-arg SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)"
> cat: /Users/********/.ssh/id_rsa: No such file or directory
```

I will break it down to be more step-by-step. I think the issue was the lack of clarity here. The id_rsa is meant to be replacement with the key identification file name such as id_ed12345. But since they are public I think will no longer need the --build-arg portion anymore.

**Comment by dchassin** [comment]
> > Here is a transcript of my attempt:
> > ```
> > ********
> > openfido-auth-service$ docker-compose build --build-arg SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)"
> > cat: /Users/********/.ssh/id_rsa: No such file or directory
> > ```
> 
> I will break it down to be more step-by-step. I think the issue was the lack of clarity here. The id_rsa is meant to be replacement with the key identification file name such as id_ed12345. But since they are public I think will no longer need the --build-arg portion anymore.

I realize that now.  I'm still plowing through it.

**Comment by dchassin** [comment]
Now it fails as follows:

~~~
openfido-app-service$ docker-compose build
blobstorage uses an image, skipping
workflow-db uses an image, skipping
auth-db uses an image, skipping
app-db uses an image, skipping
WARNING: Native build is an experimental feature and could change at any time
Building workflow-queue
[+] Building 0.6s (5/5) FINISHED                                                                                                             
 => [internal] load build definition from Dockerfile.rabbitmq                                                                           0.0s
 => => transferring dockerfile: 81B                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                       0.0s
 => => transferring context: 34B                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/rabbitmq:3-alpine                                                                    0.5s
 => CACHED [1/1] FROM docker.io/library/rabbitmq:3-alpine@sha256:5b9f3d10555376369526d81eb07697255383f8c84aa5f3b34164d43f9ba60d0e       0.0s
 => exporting to image                                                                                                                  0.0s
 => => exporting layers                                                                                                                 0.0s
 => => writing image sha256:39ab86d112f9c1a84e8badd5bf5002c551ff6bb8141ebe2216ccd1b8903f8fbc                                            0.0s
 => => naming to docker.io/library/openfido-app-service_workflow-queue                                                                  0.0s
Successfully built 39ab86d112f9c1a84e8badd5bf5002c551ff6bb8141ebe2216ccd1b8903f8fbc
Building workflow-service
[+] Building 43.8s (22/24)                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                    0.0s
 => => transferring dockerfile: 1.11kB                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                       0.0s
 => => transferring context: 34B                                                                                                        0.0s
 => resolve image config for docker.io/docker/dockerfile:1.0.0-experimental                                                             0.7s
 => CACHED docker-image://docker.io/docker/dockerfile:1.0.0-experimental@sha256:d2d402b6fa1dae752f8c688d72066a912d7042cc1727213f7990cd  0.0s
 => [internal] load .dockerignore                                                                                                       0.0s
 => => transferring context: 34B                                                                                                        0.0s
 => [internal] load build definition from Dockerfile                                                                                    0.0s
 => => transferring dockerfile: 44B                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim                                                                      0.8s
 => [base 1/1] FROM docker.io/library/python:3.8-slim@sha256:cede59c0e2fcbabed9b3094f1564917632ecdd11c25c2a275654946938225ef4           0.0s
 => [internal] load build context                                                                                                       0.0s
 => => transferring context: 1.70kB                                                                                                     0.0s
 => CACHED [internal] helper image for file operations                                                                                  0.0s
 => CACHED [python-deps 1/10] RUN apt-get update -qq && apt-get install -y ssh git                                                      0.0s
 => [python-deps 2/10] RUN mkdir /root/.ssh/                                                                                            0.4s
 => CACHED [runtime 1/4] RUN apt-get update -qq &&   apt-get install -y pipenv   postgresql-client   curl   &&   apt-get clean          0.0s
 => CACHED [runtime 2/4] RUN mkdir /opt/app                                                                                             0.0s
 => [python-deps 3/10] RUN echo "" > /root/.ssh/id_rsa                                                                                  0.3s
 => [python-deps 4/10] RUN chmod 600 /root/.ssh/id_rsa                                                                                  0.3s
 => [python-deps 5/10] RUN touch /root/.ssh/known_hosts                                                                                 0.3s
 => [python-deps 6/10] RUN ssh-keyscan github.com >> /root/.ssh/known_hosts                                                             0.5s
 => [python-deps 7/10] ADD Pipfile .                                                                                                    0.2s 
 => [python-deps 8/10] ADD Pipfile.lock .                                                                                               0.2s 
 => [python-deps 9/10] RUN pip install pipenv                                                                                           6.6s
 => ERROR [python-deps 10/10] RUN --mount=type=ssh PIPENV_VENV_IN_PROJECT=1 pipenv install --dev --deploy                              33.2s
------                                                                                                                                       
 > [python-deps 10/10] RUN --mount=type=ssh PIPENV_VENV_IN_PROJECT=1 pipenv install --dev --deploy:                                          
#22 1.083 Creating a virtualenv for this project...                                                                                          
#22 1.083 Pipfile: /Pipfile                                                                                                                  
#22 1.100 Using /usr/local/bin/python3.8 (3.8.7) to create virtualenv...                                                                     
⠦ Creating virtual environment...created virtual environment CPython3.8.7.final.0-64 in 426ms                                                
#22 1.661   creator CPython3Posix(dest=/.venv, clear=False, no_vcs_ignore=False, global=False)
#22 1.661   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
#22 1.661     added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
#22 1.661   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
#22 1.661 
#22 1.666✔ Successfully created virtual environment! 
#22 1.785 Virtualenv location: /.venv
#22 1.834 Installing dependencies from Pipfile.lock (47ba74)...
#22 31.67 An error occurred while installing -e git+ssh://git@github.com/slacgismo/openfido-utils.git@6544e1878690c41c4d064f476bb82559905b4e56#egg=openfido-utils! Will try again.
#22 31.67 Installing initially failed dependencies...
#22 32.79 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/cli/command.py", line 233, in install
#22 32.79 [InstallError]:       retcode = do_install(
#22 32.79 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 2052, in do_install
#22 32.79 [InstallError]:       do_init(
#22 32.79 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 1304, in do_init
#22 32.79 [InstallError]:       do_install_dependencies(
#22 32.79 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 899, in do_install_dependencies
#22 32.79 [InstallError]:       batch_install(
#22 32.79 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 796, in batch_install
#22 32.79 [InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
#22 32.79 [InstallError]:   File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 703, in _cleanup_procs
#22 32.79 [InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
#22 32.79 [pipenv.exceptions.InstallError]: Obtaining openfido-utils from git+ssh://****@github.com/slacgismo/openfido-utils.git@6544e1878690c41c4d064f476bb82559905b4e56#egg=openfido-utils (from -r /tmp/pipenv-6h_di4mu-requirements/pipenv-g9bpy_a8-requirement.txt (line 1))
#22 32.79 [pipenv.exceptions.InstallError]:   Cloning ssh://****@github.com/slacgismo/openfido-utils.git (to revision 6544e1878690c41c4d064f476bb82559905b4e56) to /.venv/src/openfido-utils
#22 32.79 [pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/slacgismo/openfido-utils.git' /.venv/src/openfido-utils Check the logs for full command output.
#22 32.79 ERROR: Couldn't install package: openfido-utils
#22 32.79  Package installation failed...
------
executor failed running [/bin/sh -c PIPENV_VENV_IN_PROJECT=1 pipenv install --dev --deploy]: exit code: 1
ERROR: Service 'workflow-service' failed to build
~~~

**Review by dchassin — APPROVED** [review]

**Comment by dchassin** [comment]
The simple startup command is working really well.  Let's focus on having users use that command instead of all the more complete developer stuff.

~~~
docker run --rm \
  -v /tmp:/tmp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -p 127.0.0.1:5001:5001 \
  -p 127.0.0.1:5002:5002 \
  -p 127.0.0.1:5003:5003 \
  -p 127.0.0.1:9000:9000 \
  -p 127.0.0.1:3000:3000 \
  openfido/openfido
~~~

**Comment by avpeery** [comment]
> The simple startup command is working really well. Let's focus on having users use that command instead of all the more complete developer stuff.
> 
> ```
> docker run --rm \
>   -v /tmp:/tmp \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   -p 127.0.0.1:5001:5001 \
>   -p 127.0.0.1:5002:5002 \
>   -p 127.0.0.1:5003:5003 \
>   -p 127.0.0.1:9000:9000 \
>   -p 127.0.0.1:3000:3000 \
>   openfido/openfido
> ```

I think the issue is that this set up is fine for exampling an initial set up of how the site works, but is not for local development purposes.

**Pull request merged**
